name: minify js
run-name: Minify production code
on:
  push:
    paths:
      - 'script.js'
    branches:
      - 'main'

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install NodeJS and CLI tools
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g terser

      # Perform minification, overwriting original files
      - run: terser --compress --mangle --output script.js script.js

      # (Force) push changes to `gh-pages` branch
      - run: |
          git config user.name Aaron
          git config user.email 79121360+UnrealApex@users.noreply.github.com
          git commit -am 'Automated minify of script.js'
          git push --force -u origin main:gh-pages
